version: '2'
services:
 zabbix-server:
  build: ./server-mysql/ubuntu
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ${ZBX_PLACE}/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${ZBX_PLACE}/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
  volumes_from:
   - zabbix-snmptraps:ro
  links:
   - mysql-server:mysql-server
   - zabbix-snmptraps:zabbix-snmptraps
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
   mem_limit: 512m
  env_file:
   - .env_db_mysql
   - .env_srv
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-server
     - zabbix-server-mysql
     - zabbix-server-ubuntu-mysql
     - zabbix-server-mysql-ubuntu
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "ubuntu"

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-3.0-latest
  restart: always
  ports:
   - "80:80"
   - "443:443"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  mem_limit: 512m
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ${ZBX_PLACE}/zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
  env_file:
   - .env_db_mysql
   - .env_web
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-web-apache-mysql
     - zabbix-web-apache-ubuntu-mysql
     - zabbix-web-apache-mysql-ubuntu
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "ubuntu"

 zabbix-agent:
  build: ./agent
  restart: always
  ports:
   - "10050:10050"
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ${ZBX_PLACE}/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_agent
  user: root
  privileged: true
  pid: "host"
  networks:
   zbx_net:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-ubuntu
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "ubuntu"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:ubuntu-3.0-latest
  restart: always
  ports:
   - "162:162/udp"
  volumes:
   - ${ZBX_PLACE}/zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
  user: root
  networks:
   zbx_net:
    aliases:
     - zabbix-snmptraps
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix SIA"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 mysql-server:
  image: mysql:5.7
  restart: always
  volumes_from:
    - db_data_mysql
  volume_driver: local
  env_file:
   - .env_db_mysql
  user: root
  networks:
   zbx_net:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 db_data_mysql:
    image: busybox
    volumes:
    - ${ZBX_PLACE}/zbx_env/var/lib/mysql:/var/lib/mysql:rw

networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1

